version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    build: .
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py migrate --run-syncdb"
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration